### PR TITLE
Feature/issue 5

### LINKED ISSUE #5: Display Recall Product Information
As a consumer user, I want to see details on a recalled product to determine if it impacts my area.

Acceptance Criteria:
1. Display product description
2. Display reason for recall
3. Display recalling firm
4. Display recall initiation date
5. Display status
6. Display distribution pattern
7. Display code info
8. Display classification

### PR DESCRIPTION
**Pull request by jvillarreal-kpmg**
Display Recall Product Information

Fixes #5

### CODE REVIEW

**Comment by jardilio-kpmg** [comment]
@jvillarreal-kpmg please pull back from develop into your branch to update and resolve conflicts so we can merge. Also, appears you still have failing tests in your build: http://ec2-52-1-174-71.compute-1.amazonaws.com:8080/job/ads-rfq-prototype/42/

**Comment by jardilio-kpmg** [comment]
Here is the updated screen:

image

@jvillarreal-kpmg , @shavensKPMG and I spoke about this, don’t do the footer on this page. Instead, keep the overflow button in the upper right and put 2 items in it:

Search (with search icon) href=#/recalls/search
Add to List (with add icon) disabled

**Comment by jvillarreal-kpmg** [comment]
Thanks,

Just wanted to confirm that from the original issue: 
https://github.com/jardilio-kpmg/ads-rfq-prototype/issues/5

Those marked with an X are not displayed from latest comp:
1. Display product description
2. Display reason for recall
3. Display recalling firm X
4. Display recall initiation date
5. Display status X
6. Display distribution pattern
7. Display code info
8. Display classification

**Comment by jardilio-kpmg** [comment]
Lets go ahead and add those missing fields to the view, create new cards for each like others.

**Comment by jvillarreal-kpmg** [comment]
All done.

One final observation is that api have an specific format in their date results. Do we wan't to keep their date format or we apply the one shown in the comp.

**Pull request merged**
